### ISSUE TITLE
[BUG] Section 1 - MUI error in 1.2

### ISSUE THREAD

**Issue by julia-rom** [globalmangrovewatch/gmw-users#112]
**Describe the bug**

Autocomplete error where the value provided is invalid. This comes from the countries list.

**To Reproduce**
1. Go to Project details
2. Go to 1.2
3. Select counrty

**Expected behavior**
The countries list should be a valid value.

**Screenshots**
<img width="341" alt="Screen Shot 2022-06-13 at 1 17 35 PM" src="https://user-images.githubusercontent.com/26089140/173409452-012755f2-d0e2-47d2-b3f9-758504613241.png">

**Comment by mmnoo** [comment]
These were the same errors that I saw and fixed in the new sites form work I did here https://github.com/globalmangrovewatch/gmw-users/pull/110#discussion_r894912145
