### ISSUE TITLE
[FEATURE] Add Transifex for translations

### ISSUE THREAD

**Issue by JBurkinshaw** [globalmangrovewatch/gmw-users#14]
Add [Transifex Live](https://docs.transifex.com/live/introduction) to the application.

**Describe the solution you'd like**
GMW currently uses Transifex Live in [mangrove-atlas](https://github.com/Vizzuality/mangrove-atlas). Follow the documentation [here](https://docs.transifex.com/live/webmasters) and use [mangrove-atlas](https://github.com/Vizzuality/mangrove-atlas/blob/816898a4b56672ee822c2333a21e253e335fe1aa/src/components/language-selector/component.js#L24-L42) as an example of how to implement this.

Will need to obtain API key - @lhilarides is likely to be able to assist with this.

**Describe alternatives you've considered**
This is GMW's preferred solution as it is already being used in their other applications.

**Comment by comradekingu** [comment]
Running spooky scripts on your site is less than optimal.
Checking out Weblate is my tip for how to succeed with libre software translation. :)

**Comment by mmnoo** [comment]
Sparkgeo people see https://sparkgeo.slack.com/archives/C036D4TLVPT/p1657749863253699?thread_ts=1657738411.066559&cid=C036D4TLVPT for instructions to get key
