### ISSUE TITLE
form nav

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#143]
wire up public private. FE devs figure out the payload and tell angelo

**Comment by alanjleonard** [comment]
![image](https://user-images.githubusercontent.com/35936230/178021452-4e2f0fe7-8b26-4ddc-ad44-03271feca506.png)

At the top of every section page show a fixed navigation so users are able to easily save and navigate sections as well as see the data-privacy setting for that section.

Buttons from left to right in the screen shot
1. Go back to site overview page (list of sections). Same icon as sites with left arrow underneath. 
2.  Go to previous section (disable if at section one)
3. Go to next section (disable if at last section - Navigate through sections in the same order they'd appear on the site overview page.)
4. Set data privacy dropdown. `<select>` with the options for `Public` and `Private`. Default to the default privacy setting when the site was created.
5. Save button. Saves the form.

Below that, show the current site name.
