### ISSUE TITLE
add date info to site card in site list (needs api work first)

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#160]
Just the date, not who edited it

![Image](https://user-images.githubusercontent.com/1740152/176524076-7de1b29d-63e6-46a8-8abb-adaa46ea845a.png)

**Comment by ghelobytes** [comment]
API should now reflect `section_last_updated` for each site.
![image](https://user-images.githubusercontent.com/1610267/177243861-d88ab164-a164-45a1-92e8-823f67586066.png)
