### ISSUE TITLE
[FEATURE] Create geojson countries file from CSV

### ISSUE THREAD

**Issue by JBurkinshaw** [globalmangrovewatch/gmw-users#19]
A CSV file containing mangrove countries has been provided. Write a script to create a geojson file from this CSV for use in the MRTT UI. The bounding box for selected countries will be used to determine the extent of the map described in #17.

**Describe the solution you'd like**
- The CSV contains columns for point coordinates (`Latitude` and `Longitude`), along with min and max x and y coordinate columns.
- Use `Latitude` and `Longitude` to populate the geojson [geometry](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1) property.
- Use the min and max x an y coordinate columns to populate the [bbox](https://datatracker.ietf.org/doc/html/rfc7946#section-5) property.
- The output can be validated at [geojson.io](http://geojson.io).
- Create a new branch from `main` named `feature/19/countries-geojson`.
- Add the output file to a new directory: `gmw-users/mrtt-ui/src/data`.

Here's an example:
```js
{
  "type": "FeatureCollection",
  "features": [
     {
         "type": "Feature",
         "bbox": [70.06346893, 12.41236115, -69.86541748, 12.62402916],
         "geometry": {
             "type": "Point",
             "coordinates": [-69.97027576, 12.50931542]
         },
         "properties": {
             "country": "Aruba",
             "mangroves": 1
         }
     },
     // next feature...
  ]
}
  ```

**Describe alternatives you've considered**
There could be an alternative geojson schema so feel free to propose one.
Geojson is a good format in this case as it is human and machine readable. Properties can be used to populate form elements and the geometry/bbox/properties can be used on a web map.

**Comment by JBurkinshaw** [comment]
I wrote something to do create the geojson:
```python
features = []
with open('Mangrove_Countries.csv', newline='', encoding='latin1') as csvfile:
    print(csvfile)
    reader = csv.reader(csvfile, dialect=csv.excel, delimiter=',')
    next(reader, None)  # skip the headers
    for Country,Mangroves,Latitude,Longitude,MIN_POINT_X,MAX_POINT_X,MIN_POINT_Y,MAX_POINT_Y in reader:
        Latitude, Longitude = map(float, (Latitude, Longitude))
        features.append(
            Feature(
                bbox= [MIN_POINT_X, MIN_POINT_Y, MAX_POINT_X, MAX_POINT_Y],
                geometry = Point((Longitude, Latitude)),
                properties = {
                    'country': Country,
                    'mangroves': Mangroves
                }
            )
        )

collection = FeatureCollection(features)
with open("mangrove_countries.json", "w") as f:
    f.write('%s' % collection)
```
There was one trick with the encoding. It's not actually utf-8 encoding. One of the answers [here](https://stackoverflow.com/questions/58421078/unicodedecodeerror-utf-8-codec-cant-decode-byte-0xc9-in-position-388-invali) pointed me in the right direction.

**Comment by ghelobytes** [comment]
@JBurkinshaw @cpapalaz We'll probably just need the countries with mangrove. That is `Magroves = 1` in the csv.

**Comment by ghelobytes** [comment]
I also created this species per country list.
[country_specie.json.zip](https://github.com/globalmangrovewatch/gmw-users/files/8689314/country_specie.json.zip)

**Comment by JBurkinshaw** [comment]
> @JBurkinshaw @cpapalaz We'll probably just need the countries with mangrove. That is `Magroves = 1` in the csv.

So far I've been filtering on the client side but it would be fine to remove before then too.
