### ISSUE TITLE
Bug: site interventions doesnt load with some sites/clean out old sites from api

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#195]
works: http://localhost:3000/sites/1/form/site-interventions
Doesnt work: http://localhost:3000/sites/9/form/site-interventions

**Comment by julia-rom** [comment]
Already messaged @mmnoo but will add here for transparency:

This will be an issue for older sites. Reason is that I was submitting section 6 forms, then eventually changing the form data structure around so some fields no longer exist which is causing the page to break. If you create new sites, this shouldn't be an issue.

I think we need to do a data clean up so we can avoid pages breaking. That being said, I am still creating new sites often to test form sections and then updating form data structures as I go.

I think this is fine for devs, but the mangrove team should either be aware of this, or have a different view, with cleaned up data!
