### ISSUE TITLE
Implement site privacy in UI (wait for api)

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#199]

**Comment by mmnoo** [comment]
see https://github.com/globalmangrovewatch/gmw-users/issues/197

**Comment by mmnoo** [comment]
confirm format before start

**Comment by ghelobytes** [comment]
API changes done https://github.com/globalmangrovewatch/gmw-users/issues/197#issuecomment-1185853572

**Comment by mmnoo** [comment]
Currently there is no default section privacy input for site creation (see #197 AC). Made a ticket for that. https://github.com/globalmangrovewatch/gmw-users/issues/259
