### ISSUE TITLE
[FEATURE] Develop style guidelines

### ISSUE THREAD

**Issue by JBurkinshaw** [globalmangrovewatch/gmw-users#21]
Develop style guidelines based on existing [mangrove-atlas](https://mangrove-atlas.herokuapp.com) application ([styles in repo](https://github.com/Vizzuality/mangrove-atlas/tree/develop/src/styles)) and the [MUI](https://mui.com/) framework being used in the MRTT UI.

**Describe the solution you'd like**
Ideally a [MUI theme](https://mui.com/material-ui/customization/theming/) as close as GMW's mangrove-atlas styling as possible. There's a community [theme builder](https://bareynol.github.io/mui-theme-creator/) which could make this pretty simple.

Alternatively, @alanjleonard could provide a clear list of style guidelines and @julia-rom and I could work those into a MUI style.

**Describe alternatives you've considered**
Considered taking the style files from mangrove-atlas and using them in this application. However, it was decided that a large amount of additional work would be required to achieve the feature richness and styling required in this application with basic HTML form elements. MUI provides a lot more out of the box and is relatively simple to style.

**Comment by JBurkinshaw** [comment]
A few thoughts on this:
1. The API route contains form type (e.g. `.../registration_answers`, `.../intervention_answers`, `.../monitoring_sequence`). I don't see a reason why `question_form_type` needs to be included in the request body because of this.
2. Maybe we only need `question_id` and `answer_value` within an answer object (possibly `answer_other` as well but I am struggling to remember its purpose). Does the API need to be aware of the other property values?
      -  Can the UI be responsible for ensuring the answers in the payload are for the questions related to a specific form section?
      - Does the UI need to tell the API what the `question_parent_id` and `question_type` are or can the API be trusted to know that based on what the `question_id` is?
3. I might be wrong on this, but would it make sense to use PUT to submit all answers and POST only to create a new monitoring sequence? Other than creating a new monitoring sequence, does POST do something PUT cannot? From [these docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT):
    > The HTTP PUT request method creates a new resource or replaces a representation of the target resource with the request payload.
    > The difference between PUT and [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) is that PUT is idempotent: calling it once or several times successively has the same effect (that is no side effect), whereas successive identical POST requests may have additional effects, akin to placing an order several times.

**Comment by JBurkinshaw** [comment]
@alanjleonard is working on a style guide here: https://preview.uxpin.com/469e489ef01e6679bccb758893aaa642c7ebec40#/pages/149925044/specification/sitemap?mode=i

**Comment by julia-rom** [comment]
to add to this task : remove sass and add at a global level using a custom theme file
