### ISSUE TITLE
Bug: new site initializes with wrong last updated date

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#210]
Steps to reproduce:
- create new site
- on sites page, new site shows last updated date way in the past

Expected behaviour: Last updated date should show the date that the site was created.

![Image](https://user-images.githubusercontent.com/1740152/179266890-455a15ee-f3d3-4272-ae6f-f545e938d866.png)

**Comment by ghelobytes** [comment]
@mmnoo UI will probably need to handle `null` dates.
This is a case of existing site but no answers yet (thus no updates to any section yet)
![image](https://user-images.githubusercontent.com/1610267/179287519-bda7fad1-f8a6-4875-80bd-ee09611704c2.png)

**Comment by mmnoo** [comment]
Im just going to remove the last updated info if the server says its null. This will probably not be a problem once combine creating a new site and section 1 to be the same thing (not highest priority for this phase). Its weird that they were separated in mockups and the back end, but Im sure it made sense at the time.
