### ISSUE TITLE
[BUG] Shouldn't have to define which are primary and co-benefit for "none" and "unknown"

### ISSUE THREAD

**Issue by alanjleonard** [globalmangrovewatch/gmw-users#247]
![image](https://user-images.githubusercontent.com/35936230/185459591-f33dd4e3-edfc-487d-9e5b-2945815342ac.png)

Question 3.1, 3.2, 3.3
When you select "none" and/or "unknown", it still prompts you to select how stakeholders benefit. This doesn't make sense for none and unknow options since there are no aims for the stakeholders to benefit from.

**Comment by julia-rom** [comment]
@mmnoo not sure if you want to tackle this one since you worked on this section - but if you're deep in other tasks I can take a look at this one
