### ISSUE TITLE
[BUG] extra menu items in question 7.3

### ISSUE THREAD

**Issue by alanjleonard** [globalmangrovewatch/gmw-users#248]
In question 7.3, there's `Funder Name`, `Funder Type`, and `Percentage` in the `type` dropdown. These aren't suppoed to be in that list, they're fields for the other inputs of that question.

![Image](https://user-images.githubusercontent.com/35936230/185486634-19d3cef9-f79b-469e-8035-e3d313d8fb15.png)

**Comment by julia-rom** [comment]
good catch @alanjleonard will remove the extra items
