### ISSUE TITLE
[CHORE] Section 6 general clean up

### ISSUE THREAD

**Issue by julia-rom** [globalmangrovewatch/gmw-users#251]
from feedback on MRTTT site. Clarify with Mangrove team

Q6.1
There should be a dropdown box when you select a stakeholder to define whether they were paid or voluntary.

Q6.2a
I think the intervention dates were for all interventions, not each one? So should be a separate question?

Q6.2b
There might be seedlings or propagules from multiple sources but this only allows for one?

Q6.2c
Should state Species name not Species type, then name in the box. Also should be Number above the number box (not count)

Q6.3d
The option ‘Other’ is listed twice

**Comment by alanjleonard** [comment]
Will follow up with Mangrove team.
