### ISSUE TITLE
Cause of decline validation dead end

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#270]
Steps to reproduce:
- create a new site
- navigate to causes of decline
- do nothing, Click save button

Expected result: the form is saved and a success toast shows

Actual results:
Validation error message shows (after #202 is merged, otherwise nothing happens, and the form is not saved)

![Image](https://user-images.githubusercontent.com/1740152/187785854-0eae3b27-2cc4-4cbf-9647-bdb05fd9e0c7.png)

**Comment by julia-rom** [comment]
thanks for catching this @mmnoo , will take a look
