### ISSUE TITLE
Double check ISO date format for all dates in Database

### ISSUE THREAD

**Issue by alanjleonard** [globalmangrovewatch/gmw-users#277]

**Comment by ghelobytes** [comment]
Checked `registration_answers` table today and got mixed date formats:


![Image](https://user-images.githubusercontent.com/1610267/188704501-d7bc3096-c0ac-4b80-a144-dea04c28c034.png)

**Comment by julia-rom** [comment]
it looks like the default date wasn't being set to ISO (if one wasn't selected). Should [be fixed here. ](https://github.com/globalmangrovewatch/gmw-users/pull/282)
