### ISSUE TITLE
[FEATURE] Create Heroku app, add repo and enable review apps

### ISSUE THREAD

**Issue by JBurkinshaw** [globalmangrovewatch/gmw-users#3]
Create a new heroku app and configure in a similar way to the existing `mangrove-atlas` application. 

**Describe the solution you'd like**
Once the repo is configured, create a pipeline in the deploy settings and enable review apps.

**Describe alternatives you've considered**
We could potentially use github actions to handle the CI/CD piece but historically, GMW has used Heroku so let's go with that.

**Comment by JBurkinshaw** [comment]
Update: Use github actions to create CI/CD pipeline for review/preview apps. Heroku review apps are currently not operational due to [incident 2413](https://status.heroku.com/incidents/2413)

**Comment by ghelobytes** [comment]
This is the recommended way of deploying React app:

- https://create-react-app.dev/docs/deployment#heroku
- https://blog.heroku.com/deploying-react-with-zero-configuration#zero-configuration-deploy-to-heroku

**Comment by ghelobytes** [comment]
Will probably need to set the buildpack:
```
$ curl -n -X PUT https://api.heroku.com/apps/$APP_ID_OR_NAME/buildpack-installations \
  -d '{
  "updates": [
    {
      "buildpack": "https://github.com/heroku/heroku-buildpack-ruby"
    }
  ]
}' \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3"
```
But `buildpack` should be set to `https://github.com/mars/create-react-app-buildpack.git`
