### ISSUE TITLE
Site last updated date null when should have date

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#326]
Steps to reproduce

- create a new site. 
- find the new site in the sites list (its not at the top? or near the top?)
- go to any form and edit and save the form
- go back to the sites list

Expected results: the newly edited site should be listed at the top of the sites list and show info on when it was last updated.

Actual results: there are a bunch of sites with no last updated dates cluttering the top section of sites

Extra info. The data from the server has null values for `section_last_updated` for sites that had just been updated.

**Comment by ghelobytes** [comment]
Fix deployed to `test` env.
