### ISSUE TITLE
Last updated date in sites list not working for all site forms

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#331]
Steps to reproduce
- make a new site
- click on new site in sites list
- go to Add Monitoring Section  and add a SOCIOECONOMIC AND GOVERNANCE STATUS AND OUTCOMES form
- make some edits in the form and save it. 
- go back to the sites list

Expected results: The site should be near the top of the list if not at the very top. The last updated date property should show today's date

Actual results: The site has no last updated date and is randomly sorted.

**Comment by mmnoo** [comment]
REsponse from server for /sites (partial, for site in question)

 {
        "id": 249,
        "site_name": "alder",
        "landscape_id": 42,
        "landscape_name": "user2 landscape",
        "section_last_updated": null,
        "section_data_visibility": {
            "1": "public",
            "2": "public",
            "3": "public",
            "4": "public",
            "5": "public",
            "6": "public",
            "7": "public",
            "8": "public",
            "9": "public",
            "10": "public"
        }
    },

**Comment by ghelobytes** [comment]
Fixed.
