### ISSUE TITLE
[DOCUMENTATION] Update root directory readme

### ISSUE THREAD

**Issue by JBurkinshaw** [globalmangrovewatch/gmw-users#40]
Update README.md in the gmw-users root directory.

**Describe the solution you'd like**
~~Add relevant information about the repo, including:~~
~~- General description of monorepo approach~~
~~- Branch naming~~
~~- Conventional commits~~
~~- Creating issue (assign labels, project etc)~~
~~- (Potentially more)~~

**Comment by mmnoo** [comment]
Opted to not include process in the readme since there is a good enough chance we will handoff the project and a new team will prefer a new process. 

If we continue, we can add process instructions when and if new devs join the team.
