### ISSUE TITLE
Q 5.3g

### ISSUE THREAD

**Issue by alanjleonard** [globalmangrovewatch/gmw-users#56]
From the Framework document:
**Question text:**
What physical site measurements were taken?

**Notes**
Only complete question if the answer to Q5.3 is ‘Yes’. 
Prior to the project activities what physical site measurements were recorded at the site. Suggested parameters are provided; however users can add rows to the table to provide alternative measurements. 

**Interaction mockup:**
https://preview.uxpin.com/1aca6b2d248ca441908a2bcb243726f08fc60fcf#/pages/150080002/simulate/no-panels?mode=i

![question5-3g](https://user-images.githubusercontent.com/35936230/168382760-cee75a55-09b9-49ad-b61f-38a855640649.png)

**Description:**
- List the default site measurements 
- Under the list, add an "add another row" button
- when the user clicks this button add another row with 3 fields
- - Measurment
- - Value
- - Unit
- Inputs should be input type text since the value is unknown.
- Show a button with an "X" at  the end or the row, when the user clicks this, remove the row unprompted.

**Comment by julia-rom** [comment]
so with add another row, this will be a text input for measurement right? A user will be able to add any custom field they want? So react hook form accommodates for this - we can append items within the UI for the rows. I think this will likely take a week to build.

**Comment by alanjleonard** [comment]
Yes, I think that all three fields should be text input since we don't know what the value is going to be.

**Comment by mmnoo** [comment]
SAme estimate with a 2x for the fact that we dont code full time/ inevitable gotchas
