### ISSUE TITLE
[BUG/Feature] fix heroku deployment / figure out somewhere to serve app for testing

### ISSUE THREAD

**Issue by mmnoo** [globalmangrovewatch/gmw-users#68]
This ticket will be expanded later. Just placeholder for now.

noticed during dev that our pr review apps are failing to build. We have agreed that we dont need per PR review apps if we have to move fast for a deadline. We do however need a place to serve the app for testing and eventually production.

See this slack thread https://sparkgeo.slack.com/archives/C036D4TLVPT/p1653063247787369

https://devcenter.heroku.com/articles/deploying-nodejs

**Comment by ghelobytes** [comment]
Fixed by https://github.com/globalmangrovewatch/gmw-users/pull/69
