### ISSUE TITLE
Question 3.4 inline with 3.1, 3.2, 3.3

### ISSUE THREAD

**Issue by alanjleonard** [globalmangrovewatch/gmw-users#72]
Question 3.4 will be merged in with questions 3.1, 3.2, and 3.3. There will be no more question 3.4

Question 3.1, 3.2, and 3.3 are all different types of aims. When the user selects one of these aims, a new question will appear underneath the selected checkbox. List the responses from Q2.1 (leave empty if there are no responses in Q2.1) with the question  text from 3.4: "identify which are primary, or co-benefits"

For each of the selected stakeholders selected in Q2.1, show a dropdown with the options:
- Primary aims
- Co-benefits
- Neither

TODO: Notify the user if they've already filled out question 3.1, 3.2, or 3.3 then add a new selection to Q2.1.

![Image](https://user-images.githubusercontent.com/35936230/170092455-2eaa908a-3b22-4851-a1aa-af7129c37b05.png)

**Comment by mmnoo** [comment]
added acceptance criteria: when a user unselects and aim the stakeholder benefits from that aim clears and is removed from the api on submit
