### ISSUE TITLE
Q6.2b & 6.2C

### ISSUE THREAD

**Issue by alanjleonard** [globalmangrovewatch/gmw-users#79]
When the user selects a species, show the question text for 6.2c and checkboxes for `seedling` and `propagule`.
If a use selects either checkbox, show a dropdown for `source` and a numeric input for `count`. 
N.B. The options in the `Source` dropdown are different for `seedling` and `propagule`

![mockup6-2c](https://user-images.githubusercontent.com/35936230/170721979-7c7d51f3-5086-4771-99e7-5623c261f412.png)

**Comment by mmnoo** [comment]
3-10 days (of time, not billed hours, buffered for gotchas etc)

**Comment by julia-rom** [comment]
@alanjleonard do you know what are all the options are in the drop down for source?
