### ISSUE TITLE
Q7.3 Tabular input group

### ISSUE THREAD

**Issue by julia-rom** [globalmangrovewatch/gmw-users#81]
- includes name input, multi-select dropdown, and percentage input

- Only complete question if the answer to Q7.1 is ‘Monetary’

**Comment by alanjleonard** [comment]
Display the sum of all the "Percentage of funding" values below the question text and keep it sticky at the top of the page.
Default value for Percentage of funding should be 0
Removing the funder will remove the "Percentage of funding" from the calculation
User is able to add multiple funders

Ideally: should not be able to save form if the total value is greater than 100%.

![Q7 3](https://user-images.githubusercontent.com/35936230/171884609-4de2adf8-59e7-4a74-8f24-3df9ed63cbb4.png)
